name: Django and PostgreSQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        uses: docker compose build

      - name: Start services with Docker Compose
        run: docker compose up -d

      - name: Run tests
        run: docker compose exec -T web python3 manage.py migrate
